name: Fetch Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: install py package
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run python script
        env: 
            LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
            CSRF_TOKEN: ${{ secrets.CSRF_TOKEN }}
        run: python scripts/fetch_submissions.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data"

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
